language: python
python:
  # only 3.6 because I like f-strings
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python -m pytest